#ls("package:BOIN")
#system('R CMD Rd2pdf man/')
#system('R CMD Rd2pdf BOIN2.6/')


# # Generated by roxygen2: do not edit by hand
# importFrom("stats", "pbeta", "pbinom", "qbeta", "rbinom", "runif")
# export(get.boundary)
# export(get.oc)
# export(get.oc.comb)
# export(next.comb)
# export(next.subtrial)
# export(select.mtd)
# export(select.mtd.comb)
# export(summary.boin)
# export(plot.boin)



